minimum_pre_commit_version: "4.2.0"
default_install_hook_types:
  - pre-commit
  - pre-push
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        always_run: true
        entry: uv run ruff check .
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format --check
        always_run: true
        entry: uv run ruff format --check .
        language: system
        pass_filenames: false
      - id: pyright
        name: pyright
        always_run: true
        entry: uv run pyright
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        always_run: true
        entry: uv run pytest
        language: system
        pass_filenames: false
        stages:
          - pre-push
      - id: bandit
        name: bandit
        always_run: true
        entry: uv run bandit -q -r src
        language: system
        pass_filenames: false
        stages:
          - pre-push
